### ISSUE TITLE
tabelog: Improvements update

### ISSUE THREAD

**Issue by darumalab** [darumalab/Misc#1]
Comments when Improvements are being made to the code. I appreciate your assistance or advice regarding the updates.

**Comment by darumalab** [comment]
current output
<img width="1112" alt="bfe5a3be-81f5-4cb9-b0ff-967510e92aad" src="https://cloud.githubusercontent.com/assets/24467497/25068837/6c4aa070-22aa-11e7-95ff-a118d4ed7ce1.png">

**Comment by darumalab** [comment]
current data frame
<img width="935" alt="ae556096-c0af-4529-85e0-937bff8faa74" src="https://cloud.githubusercontent.com/assets/24467497/25069114/cb19ebda-22b2-11e7-982b-7ab7a1f3073a.png">

**Comment by gmlang** [comment]
Looking good. Keep improving!
